name: Build

on: [push]

jobs:
  debug-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libnl-3-dev
        sudo apt-get install -y libnl-route-3-dev
        sudo apt-get install -y help2man
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
